version: '3'
services:
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    ports:
      - "8001:80"
    env_file:
      - .env
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./data:/server/static
      - ./logs:/server/logs

